-- Create new chicken menu items using UUIDs generated by default

-- Chicken Wings 5 PCS
INSERT INTO menu_items (name, description, base_price, category, popular, available, image_url)
SELECT 'Chicken Wings (5 pcs)', '5 pieces of delicious chicken wings', 169, 'food', false, true, NULL
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE name = 'Chicken Wings (5 pcs)');

INSERT INTO variations (menu_item_id, name, price)
SELECT id, 'Basic', 0 FROM menu_items WHERE name = 'Chicken Wings (5 pcs)'
AND NOT EXISTS (SELECT 1 FROM variations WHERE menu_item_id = menu_items.id AND name = 'Basic');

INSERT INTO variations (menu_item_id, name, price)
SELECT id, 'Premium', 20 FROM menu_items WHERE name = 'Chicken Wings (5 pcs)'
AND NOT EXISTS (SELECT 1 FROM variations WHERE menu_item_id = menu_items.id AND name = 'Premium');


-- Chicken Wings 10 PCS
INSERT INTO menu_items (name, description, base_price, category, popular, available, image_url)
SELECT 'Chicken Wings (10 pcs)', '10 pieces of delicious chicken wings (2 Flavors)', 309, 'food', false, true, NULL
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE name = 'Chicken Wings (10 pcs)');

INSERT INTO variations (menu_item_id, name, price)
SELECT id, 'Basic', 0 FROM menu_items WHERE name = 'Chicken Wings (10 pcs)'
AND NOT EXISTS (SELECT 1 FROM variations WHERE menu_item_id = menu_items.id AND name = 'Basic');

INSERT INTO variations (menu_item_id, name, price)
SELECT id, 'Premium', 20 FROM menu_items WHERE name = 'Chicken Wings (10 pcs)'
AND NOT EXISTS (SELECT 1 FROM variations WHERE menu_item_id = menu_items.id AND name = 'Premium');


-- Chicken Wings Party Tray
INSERT INTO menu_items (name, description, base_price, category, popular, available, image_url)
SELECT 'Chicken Wings Party Tray', 'Party Tray (30 PCS, 4 Flavors)', 799, 'food', false, true, NULL
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE name = 'Chicken Wings Party Tray');


-- Chicken Poppers 1 Tub
INSERT INTO menu_items (name, description, base_price, category, popular, available, image_url)
SELECT 'Chicken Poppers (1 Tub)', '1 Tub of Chicken Poppers', 139, 'food', false, true, NULL
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE name = 'Chicken Poppers (1 Tub)');

INSERT INTO variations (menu_item_id, name, price)
SELECT id, 'Basic', 0 FROM menu_items WHERE name = 'Chicken Poppers (1 Tub)'
AND NOT EXISTS (SELECT 1 FROM variations WHERE menu_item_id = menu_items.id AND name = 'Basic');

INSERT INTO variations (menu_item_id, name, price)
SELECT id, 'Premium', 20 FROM menu_items WHERE name = 'Chicken Poppers (1 Tub)'
AND NOT EXISTS (SELECT 1 FROM variations WHERE menu_item_id = menu_items.id AND name = 'Premium');


-- Chicken Poppers Party Tray
INSERT INTO menu_items (name, description, base_price, category, popular, available, image_url)
SELECT 'Chicken Poppers Party Tray', 'Party Tray (Good for 10-15 pax, 4 Flavors)', 999, 'food', false, true, NULL
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE name = 'Chicken Poppers Party Tray');


-- Chicken Tenders 2 PCS
INSERT INTO menu_items (name, description, base_price, category, popular, available, image_url)
SELECT 'Chicken Tenders (2 pcs)', '2 pieces of Chicken Tenders', 129, 'food', false, true, NULL
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE name = 'Chicken Tenders (2 pcs)');

INSERT INTO variations (menu_item_id, name, price)
SELECT id, 'Basic', 0 FROM menu_items WHERE name = 'Chicken Tenders (2 pcs)'
AND NOT EXISTS (SELECT 1 FROM variations WHERE menu_item_id = menu_items.id AND name = 'Basic');

INSERT INTO variations (menu_item_id, name, price)
SELECT id, 'Premium', 30 FROM menu_items WHERE name = 'Chicken Tenders (2 pcs)'
AND NOT EXISTS (SELECT 1 FROM variations WHERE menu_item_id = menu_items.id AND name = 'Premium');


-- Chicken Tenders 4 PCS
INSERT INTO menu_items (name, description, base_price, category, popular, available, image_url)
SELECT 'Chicken Tenders (4 pcs)', '4 pieces of Chicken Tenders', 209, 'food', false, true, NULL
WHERE NOT EXISTS (SELECT 1 FROM menu_items WHERE name = 'Chicken Tenders (4 pcs)');

INSERT INTO variations (menu_item_id, name, price)
SELECT id, 'Basic', 0 FROM menu_items WHERE name = 'Chicken Tenders (4 pcs)'
AND NOT EXISTS (SELECT 1 FROM variations WHERE menu_item_id = menu_items.id AND name = 'Basic');

INSERT INTO variations (menu_item_id, name, price)
SELECT id, 'Premium', 20 FROM menu_items WHERE name = 'Chicken Tenders (4 pcs)'
AND NOT EXISTS (SELECT 1 FROM variations WHERE menu_item_id = menu_items.id AND name = 'Premium');
